version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - my_custom_network
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=crm_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    networks:
      - my_custom_network
    restart: on-failure
    ports:
      - 8082:8081

volumes:
      db:

networks:
  # Define a custom bridge network.
  # This provides an isolated network for your services to communicate with each other.
  my_custom_network:
    # You can optionally specify a driver, 'bridge' is the default.
    driver: bridge
