# (La línea de version es opcional y obsoleta; puedes borrarla)
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crm_db
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build: .                          # Construye con tu Dockerfile multistage
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8082:8080"                   # Mapea 8082 de tu host al 8080 del contenedor
    environment:                      # Variables que tu Spring Boot espera
      SERVER_PORT: "8080"
      MYSQLHOST: mysqldb
      MYSQLPORT: "3306"
      MYSQLDATABASE: crm_db
      MYSQLUSER: root
      MYSQLPASSWORD: admin

  frontend:
    build:
      context: ../../frontend/crm-frontend     # ruta relativa desde el backend
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: on-failure
    ports:
      - "4200:80"

volumes:
  db: