server:
  port: 8081

spring:
  main:
    allow-circular-references: true
  application:
    name: crm_db
  datasource:
    url: jdbc:mysql://localhost:3306/crm_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: root
      password: "{noop}admin"

springdoc:
  swagger-ui:
    path: /crm_db.html
    operationsSorter: method